### ISSUE TITLE
Check the toml config for sewup project setup correctly

### ISSUE THREAD

**Issue by yanganto** [second-state/SewUp#140]
A sewup project need a lot of required fields in cargo.toml, please implement a check with kindly warning for user on `cargo-sewup`.

Here is the example of cargo.toml
https://github.com/second-state/SewUp/blob/main/examples/default-contract/Cargo.toml
```toml
[profile.release]
incremental = false
panic = "abort"
lto = true
opt-level = "z"

[profile.release.package.default-contract]
incremental = false
opt-level = "z"

[features]
constructor = []
constructor-test = []
```
